services: 
  frontend: 
    image: frontend
    build: ./frontend.Dockerfile
    ports: 
      - 8080:8080
  backend: 
    image: backend
    build: ./backend.Dockerfile
    ports:
      - 5000:5000
  
    
